version: "3.8"

services:
  recettes-app:
    container_name: recettes-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/data/recettes.sqlite
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3007:3000"
    volumes:
      - recettes_data:/data
    restart: unless-stopped

volumes:
  recettes_data:
